export const RESET_STATE = 'NAVIGATION_RESET_STATE';
export const CURRENT_ITEM = 'NAVIGATION_CURRENT_ITEM';

export const REQUEST_LOADING = 'NAVIGATION_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'NAVIGATION_REQUEST_SUCCESS';
export const REQUEST_FAILED = 'NAVIGATION_REQUEST_FAILED';

export const CURRENT_ACTION = 'NAVIGATION_CURRENT_ACTION';
export const RESET_ACTION = 'NAVIGATION_RESET_ACTION';
